### ISSUE TITLE
Build Error - 'Could not find symbol 'CodeMirror' 

### ISSUE THREAD

**Issue by 274188A** [mrjones2014/BlazorCMS#22]
I'm seeing :

>     Project BlazorCMS.Client
>       Client\ts\src\CodeMirrorInterop.ts:59 Could not find symbol 'CodeMirror' in external module 'CodeMirrorInterop.ts'.

👍

**Comment by mrjones2014** [comment]
@274188A did you run `npm install` first? CodeMirror should be coming from a node module. The `CodeMirror` namespace is also used before line 59 so I'm not sure why it'd be coming from there.
